language: 

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: bionic # 18.04.x

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt purge python2.7-minimal
  - sudo apt-get -y install python3 python3-h5py python3-matplotlib
  - sudo apt-get -y install python3-tk

addons:
  apt:
    update: true
    
# blocklist
#branches:
#  except:
#    - name

#branches:
#  only:
#    - master

script: 
  - ./.travis/test-qa_toolbox.sh

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
